[build]
  command = "npm install && npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = false
  optimize = false
  webp = false

[build.processing]
  skip_processing = true
