// netlify.toml file for configuring Netlify deployments

[build]
  command = "npm install && npm run build"
  publish = "_site"
  
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
