name = "amethyst-network-website"
compatibility_date = "2025-05-20"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[build.upload]
format = "directory"

[site]
bucket = "_site"

[env]
NODE_VERSION = "18"
